namespace WeatherApp.API.Providers;

public enum Language
{
    Arabic,
    Bengali,
    Bulgarian,
    ChineseSimplified,
    ChineseTraditional,
    Czech,
    Danish,
    Dutch,
    Finnish,
    French,
    German,
    Greek,
    Hindi,
    Hungarian,
    Italian,
    Japanese,
    Javanese,
    Korean,
    Mandarin,
    Marathi,
    Polish,
    Portuguese,
    Punjabi,
    Romanian,
    Russian,
    Serbian,
    Sinhalese,
    Slovak,
    Spanish,
    Swedish,
    Tamil,
    Telugu,
    Turkish,
    Ukrainian,
    Urdu,
    Vietnamese,
    WuShanghainese,
    Xiang,
    YueCantonese,
    Zulu
}

public static class LanguageExtensions
{
    public static string ToLangCode(this Language language) => language switch
    {
        Language.Arabic            => "ar",
        Language.Bengali           => "bn",
        Language.Bulgarian         => "bg",
        Language.ChineseSimplified => "zh",
        Language.ChineseTraditional => "zh_tw",
        Language.Czech             => "cs",
        Language.Danish            => "da",
        Language.Dutch             => "nl",
        Language.Finnish           => "fi",
        Language.French            => "fr",
        Language.German            => "de",
        Language.Greek             => "el",
        Language.Hindi             => "hi",
        Language.Hungarian         => "hu",
        Language.Italian           => "it",
        Language.Japanese          => "ja",
        Language.Javanese          => "jv",
        Language.Korean            => "ko",
        Language.Mandarin          => "zh_cmn",
        Language.Marathi           => "mr",
        Language.Polish            => "pl",
        Language.Portuguese        => "pt",
        Language.Punjabi           => "pa",
        Language.Romanian          => "ro",
        Language.Russian           => "ru",
        Language.Serbian           => "sr",
        Language.Sinhalese         => "si",
        Language.Slovak            => "sk",
        Language.Spanish           => "es",
        Language.Swedish           => "sv",
        Language.Tamil             => "ta",
        Language.Telugu            => "te",
        Language.Turkish           => "tr",
        Language.Ukrainian         => "uk",
        Language.Urdu              => "ur",
        Language.Vietnamese        => "vi",
        Language.WuShanghainese    => "zh_wuu",
        Language.Xiang             => "zh_hsn",
        Language.YueCantonese      => "zh_yue",
        Language.Zulu              => "zu",
        _ => throw new ArgumentOutOfRangeException(nameof(language), language, "Unhandled language.")
    };
}
